[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "block-array"
readme = "README.md"
version = "0.0.0"
dependencies = [
    "numpy"
]

[project.optional-dependencies]
petsc = ["petsc4py"]

[tool.pytest.ini_options]
testpaths = ["tests"]